version: "3.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    working_dir: /home/work
    restart: always
    volumes:
      - $PWD/configs/nginx-LB/html:/usr/share/nginx/html
      - $PWD/configs/nginx-LB/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/configs/nginx-LB/conf.d:/etc/nginx/conf.d
      - $PWD/configs/nginx-LB/logs:/var/log/nginx
  nginx-yaf-1:
    image: srcrs/nginx-yaf:latest
    ports:
      - 8082:80
    working_dir: /root
    restart: always
    command:
      - /bin/bash
      - -c
      - |
         service nginx start
         service php7.4-fpm start
         sleep infinity
    volumes:
      - $PWD/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/logs/nginx:/var/log/nginx
      - $PWD/configs/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/webroot:/var/www/html
      - $PWD/configs/php-fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - $PWD/configs/php-fpm/pool.d:/etc/php/7.4/fpm/pool.d
      - $PWD/configs/php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
  nginx-yaf-2:
    image: srcrs/nginx-yaf:latest
    ports:
      - 8083:80
    working_dir: /root
    restart: always
    command:
      - /bin/bash
      - -c
      - |
         service nginx start
         service php7.4-fpm start
         sleep infinity
    volumes:
      - $PWD/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/logs/nginx:/var/log/nginx
      - $PWD/configs/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/webroot:/var/www/html
      - $PWD/configs/php-fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - $PWD/configs/php-fpm/pool.d:/etc/php/7.4/fpm/pool.d
      - $PWD/configs/php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
