version: "3.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    working_dir: /home/work
    restart: always
    volumes:
      - $PWD/nginx/html:/usr/share/nginx/html
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/logs:/var/log/nginx
  php-apache-1:
    image: srcrs/apache-php:latest
    ports:
      - 8082:80
    working_dir: /root
    restart: always
    command:
      - /bin/bash
      - -c
      - |
         service apache2 start
         sleep infinity
    volumes:
      - $PWD/php/php.ini:/etc/php/7.4/apache2/php.ini
      - $PWD/apache-1/logs:/var/log/apache2
      - $PWD/apache-1/www/html:/var/www/html
      - $PWD/apache-1/conf:/etc/apache2
  php-apache-2:
    image: srcrs/apache-php:latest
    ports:
      - 8083:80
    working_dir: /root
    restart: always
    command:
      - /bin/bash
      - -c
      - |
         service apache2 start
         sleep infinity
    volumes:
      - $PWD/php/php.ini:/etc/php/7.4/apache2/php.ini
      - $PWD/apache-2/logs:/var/log/apache2
      - $PWD/apache-2/www/html:/var/www/html
      - $PWD/apache-2/conf:/etc/apache2
